import Head from 'next/head'
import { Container, Toolbar, Typography } from '@mui/material'
import { Box } from '@mui/system'
import Link from 'components/Link';

export default function Home() {
  return (
    <Box sx={{ width: '100vw', height: '100vh' }}>
      <Head>
        <title>NextJS and Cloudinary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md">
        <Typography variant='h2'>
          About
        </Typography>

        <Toolbar disableGutters sx={{ gap: 1 }}>
          <Link href='/'>Home</Link>
          <Link href='/masonry'>Masonry</Link>
          <Typography>About</Typography>
          <Box sx={{ flexGrow: 1 }} />
        </Toolbar>

        <Typography gutterBottom>
          This example app uses two NextJS API Routes.
        </Typography>
        <Typography gutterBottom>
          The search route searches cloudinary and returns images with a specified tag.
          This is used to fetch the images displayed below.
        </Typography>
        <Typography gutterBottom>
          The upload route uploads a photo to cloudinary.
          This is used when the Upload button is clicked.
        </Typography>
      </Container>
    </Box>
  )
}
