import Head from 'next/head'
import useSWR from 'swr';

import { Typography } from '@mui/material'
import { Box } from '@mui/system'
import Image from 'next/image'

import FileUpload from 'components/FileUpload';
import { uploadFile } from 'services/upload';
import { fetcher } from 'services/http';

const url = 'http://localhost:3000/api/search?tags=blue'

export default function Home() {
  const { data, error } = useSWR(url, fetcher)
  const loading = !error && !data

  const onFileChange = async (e) => {
    const response = await uploadFile(e.target.files[0])
    console.log(response)
  }

  const renderContent = () => {
    if (loading) {
      return <p>loading...</p>
    }

    if (error) {
      return <p>error...</p>
    }

    const images = data.data.response.resources;
    // console.log(images)

    return (
      <Box>
        {images.map(image => (
          <Box key={image.asset_id}>
            <Image src={image.url} alt={image.filename} width={image.width} height={image.height} />
          </Box>
        ))}
      </Box>
    )
  }

  return (
    <Box sx={{ width: '100vw', height: '100vh' }}>
      <Head>
        <title>NextJS and Cloudinary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ width: '100%', height: '100%', p: 2 }} component='main'>
        <Typography variant='h1'>
          NextJS and Cloudinary
        </Typography>
        <FileUpload onFileChange={onFileChange} />
        {renderContent()}
      </Box>
    </Box>
  )
}
